import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CalendarDays, Heart, MapPin, Sparkles, Users, Wallet } from 'lucide-react';

const moments = [
  { icon: CalendarDays, title: 'Map every moment', text: 'Turn one celebration or five events into a calm, shareable timeline.' },
  { icon: Users, title: 'Keep everyone included', text: 'Guests, traditions, notes, and ceremony details in one organized place.' },
  { icon: Wallet, title: 'Make the numbers feel simple', text: 'See what matters most and get budget guidance that fits your guest count.' },
  { icon: MapPin, title: 'Plan locally, beautifully', text: 'Discover vendor ideas and keep your wedding details ready to share.' },
];

export default function WhatIsVivaha() {
  const [active, setActive] = useState(0);
  const ActiveIcon = moments[active].icon;
  return <div className="min-h-screen overflow-hidden bg-[#fff8fb] text-slate-900">
    <header className="sticky top-0 z-50 border-b border-rose-100/80 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3"><Link to="/" className="flex items-center gap-2 font-bold"><span className="rounded-xl bg-gradient-to-br from-rose-500 to-pink-600 p-2 text-white"><Heart className="w-5 h-5" /></span>Vivaha</Link><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-rose-600"><ArrowLeft className="w-4 h-4" /> Back home</Link></div></header>
    <main>
      <section className="relative mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-2 md:py-24"><div className="absolute -top-20 left-1/3 h-72 w-72 rounded-full bg-rose-200/50 blur-3xl" /><div className="relative"><p className="mb-4 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-rose-600 shadow-sm"><Sparkles className="w-4 h-4" /> Wedding planning that feels personal</p><h1 className="text-5xl font-black leading-[.95] tracking-tight md:text-7xl">Your wedding has more than one story.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">Vivaha helps couples plan the details, honor their traditions, and keep everyone moving toward a celebration that actually feels like them.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-rose-500 to-pink-600 px-6 py-3 font-bold text-white shadow-lg shadow-rose-200 hover:-translate-y-0.5"><Heart className="w-4 h-4" /> Start planning</Link><a href="#tour" className="rounded-xl border border-rose-200 bg-white px-6 py-3 font-bold text-rose-700">Take the tour</a></div></div><div className="relative rounded-[2rem] bg-slate-900 p-5 shadow-2xl"><div className="rounded-[1.5rem] bg-gradient-to-br from-rose-50 to-violet-100 p-6"><p className="text-xs font-bold uppercase tracking-widest text-rose-600">Your celebration</p><h2 className="mt-2 text-3xl font-black">A plan that grows with you.</h2><div className="mt-6 grid grid-cols-2 gap-3">{['Ceremony timeline','Guest experience','Budget clarity','Vivaha AI'].map((item, i) => <div key={item} className={`rounded-2xl p-4 ${i === 0 ? 'bg-rose-500 text-white' : 'bg-white/80 text-slate-700'}`}><div className="h-2 w-10 rounded bg-current opacity-30"/><p className="mt-5 text-sm font-bold">{item}</p></div>)}</div><div className="mt-5 rounded-2xl bg-white p-4 shadow-sm"><p className="font-bold">“Help me plan a traditional ceremony and modern reception.”</p><p className="mt-2 text-sm text-slate-500">Vivaha AI turns details into next steps—without losing what matters.</p></div></div></div></section>
      <section id="tour" className="bg-white py-16"><div className="mx-auto max-w-7xl px-5"><p className="text-center text-sm font-bold uppercase tracking-widest text-rose-500">Tap through the experience</p><h2 className="mx-auto mt-3 max-w-2xl text-center text-4xl font-black">Not another generic wedding checklist.</h2><div className="mt-10 grid gap-3 md:grid-cols-4">{moments.map((moment, index) => { const Icon = moment.icon; return <button key={moment.title} onClick={() => setActive(index)} className={`rounded-2xl p-5 text-left transition ${active === index ? 'bg-slate-900 text-white shadow-xl' : 'bg-rose-50 text-slate-700 hover:bg-rose-100'}`}><Icon className="w-6 h-6" /><p className="mt-8 font-bold">{moment.title}</p></button>})}</div><div className="mt-4 grid gap-8 rounded-3xl bg-gradient-to-r from-rose-50 to-violet-50 p-8 md:grid-cols-[auto_1fr]"><div className="rounded-2xl bg-white p-5 text-rose-600 shadow-sm"><ActiveIcon className="h-10 w-10" /></div><div><h3 className="text-2xl font-black">{moments[active].title}</h3><p className="mt-2 max-w-2xl text-lg text-slate-600">{moments[active].text}</p><p className="mt-5 text-sm font-semibold text-rose-700">Click another card to explore what Vivaha does.</p></div></div></div></section>
      <section className="mx-auto max-w-4xl px-5 py-20 text-center"><Heart className="mx-auto h-8 w-8 text-rose-500"/><h2 className="mt-4 text-4xl font-black">A wedding plan that makes room for real life.</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-slate-600">Explore the journey first. Create your account whenever you are ready to save your plan.</p><Link to="/register" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-7 py-4 font-bold text-white">Get Started <ArrowRight className="w-4 h-4" /></Link></section>
    </main>
  </div>;
}
